---
- name: Disable password authentication and enable key authentication
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    regexp: '^#?PasswordAuthentication'
    line: 'PasswordAuthentication no'
    backup: yes

- name: Ensure PermitRootLogin is set to no
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    regexp: '^#?PermitRootLogin'
    line: 'PermitRootLogin no'
    backup: yes

- name: Restart SSH service
  ansible.builtin.systemd:
    name: ssh
    state: restarted
    enabled: yes

- name: Ping the server to check SSH configuration
  ansible.builtin.ping:
